<?php
namespace alei\modules\admin\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Base controller
 */
class BaseController extends Controller
{

    /**
     * 重新设定admin的布局
     */
    //public  $layout = '\admin';
    //不使用布局
    public  $layout = false;

    public function init()
    {
        $this->actionIslogin();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {

        if(Yii::$app->user->isGuest){
            $this->actionLogin();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    private function actionIslogin(){

        if (Yii::$app->user->isGuest) {

            $this->redirect("admin/site/login");
        }

    }
}
