<?php
namespace alei\modules\admin\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Base controller
 */
class BaseController extends Controller
{

    /**
     * 重新设定admin的布局
     */
    //public  $layout = '\admin';
    //不使用布局
    public  $layout = false;

    public function init()
    {
        self::actionLogin();
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actionLogin()
    {
        if (Yii::$app->user->isGuest) {
        }
    }
}